version: '3'
services:
  web:
    container_name: core-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
     - "9000:80"
     - "5000:5000"
    volumes:
      - ./api/app:/app
    depends_on:
          - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: core-db
    environment:
        SA_PASSWORD: "S4Pa55word123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./.db-data:/var/opt/mssql
    